In [3]:
import pandas as pd

In [5]:
data = pd.read_excel("Club2024.xlsx", sheet_name=None)
print(data.keys())

dict_keys(['Races', 'Overview', 'Cobbler', 'Mamores', 'Traprain', 'Allermuir', 'Arrochar', 'Blisco', 'Moffat', 'Caerketton', 'Tap O North', 'Perris Horseshoe', 'Caerketton Down', 'Run O Mill', 'Manor Water', 'Skyloop', 'Tinto'])

In [6]:
results = data[2:]

KeyError: slice(2, None, None)

In [7]:
metadata = data.pop("Races", "Overview")

In [12]:
results = data.pop("Overview")

In [13]:
data.keys()

dict_keys(['Cobbler', 'Mamores', 'Traprain', 'Allermuir', 'Arrochar', 'Blisco', 'Moffat', 'Caerketton', 'Tap O North', 'Perris Horseshoe', 'Caerketton Down', 'Run O Mill', 'Manor Water', 'Skyloop', 'Tinto'])

In [14]:
results

Empty DataFrame
Columns: [Posn, Name, Ran, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, Total]
Index: []

In [15]:
len(data)

15

In [16]:
NON_SHR = ["Blisco", "Perris Horseshoe"]
#Race data that doesn't fit the SHR table format (Usually the two british champs races

In [19]:
mamores = data["Mamores"]

In [28]:
mamores = mamores[mamores["Club"].str.startswith("Carnethy")]
#mamores['Timedelta'] = pd.to_timedelta(mamores['Time'])
mamores['Cat Pos'] = mamores.groupby('Cat')['Time'].rank(method='min', ascending=True).astype(int)

mamores = mamores.sort_values(by=['Cat', 'Time'])

mamores

     Pos             Runner          Club  Cat      Time  Cat Pos
18    19         Naomi Lang  Carnethy HRC    F  00:55:31        1
101  102       Helen Fallas  Carnethy HRC    F  01:16:28        2
2      3      Kieran Cooper  Carnethy HRC    M  00:48:51        1
11    12       Felix Wilson  Carnethy HRC    M  00:52:46        2
12    13      Csoban Balogh  Carnethy HRC    M  00:52:57        3
15    16      Ifan Oldfield  Carnethy HRC    M  00:54:35        4
27    28       Iain Gilmore  Carnethy HRC    M  00:56:56        5
20    21      Andrew Fallas  Carnethy HRC  M40  00:56:06        1
68    69       Michael Reid  Carnethy HRC  M40  01:05:35        2
77    78  Christopher Busby  Carnethy HRC  M40  01:10:50        3
38    39      Andrew Macrae  Carnethy HRC  M50  01:00:01        1
74    75    Stewart Whitlie  Carnethy HRC  M60  01:08:23        1
120  121        Drew Lennie  Carnethy HRC  M60  01:27:14        2

In [55]:
# Function to add 'Cat Pos' for each dataframe
def add_cat_pos(df):
    # Convert Time column to timedelta
    #df['Time'] = pd.to_timedelta(df['Time'])
    # Rank by Category and Time
    df['Cat Pos'] = df.groupby('Cat')['Time'].rank(method='min', ascending=True).astype(int)

    # Return the dataframe with the new 'Cat Pos' column
    return df

# Loop through each dataframe in the dictionary and apply the 'Cat Pos' function
def get_carnethies(df):
    df = df[df["Club"].str.startswith("Carnethy")]
    return df
    
for race, df in data.items():
    if race in NON_SHR:
        continue
    df = get_carnethies(df)
    data[race] = add_cat_pos(df)

data["Tinto"]

     Pos            Runner          Club  Cat      Time  Cat Pos
0      1     Joseph Wright  Carnethy HRC    M  00:30:44        1
2      3   Alistair Masson  Carnethy HRC    M  00:31:58        2
4      5       Aidan Smith  Carnethy HRC    M  00:32:51        3
8      9      Eliot Sedman  Carnethy HRC  M40  00:35:34        1
10    11     Ifan Oldfield  Carnethy HRC    M  00:35:53        4
15    16     Andrew Macrae  Carnethy HRC  M50  00:36:31        1
17    18      Iain Gilmore  Carnethy HRC    M  00:37:06        5
18    19     Andrew Lamont  Carnethy HRC  M40  00:37:14        2
20    21       Samuel Thom  Carnethy HRC    M  00:37:37        6
22    23      Drew Sharkey  Carnethy HRC  M50  00:37:48        2
28    29  Jackson Woodruff  Carnethy HRC    M  00:38:39        7
33    34    Gareth Wheeler  Carnethy HRC    M  00:38:57        8
34    35     Bryan McKenna  Carnethy HRC  M40  00:39:26        3
36    37       Neil Gordon  Carnethy HRC    M  00:39:35        9
41    42      Niamh Hunter  Carnethy HRC    F  00:40:26        1
48    49    Sebastien Menu  Carnethy HRC    M  00:41:40       10
49    50      Laura Dozier  Carnethy HRC    F  00:42:09        2
50    51      Neil Gilmore  Carnethy HRC  M60  00:42:13        1
55    56   Stewart Whitlie  Carnethy HRC  M60  00:43:10        2
61    62     James Ritchie  Carnethy HRC    M  00:43:38       11
63    64       Pippa Dakin  Carnethy HRC    F  00:43:58        3
64    65     Nathan Coombs  Carnethy HRC  M40  00:44:14        4
65    66     Kendon Martin  Carnethy HRC    M  00:44:22       12
66    67    Andy Spenceley  Carnethy HRC  M65  00:44:23        1
72    73    Rosalind Heron  Carnethy HRC    F  00:45:09        4
80    81   Jonny Pritchard  Carnethy HRC    M  00:45:38       13
81    82     Roanne Lilley  Carnethy HRC    F  00:45:44        5
84    85     Rona Fishburn  Carnethy HRC    F  00:45:54        6
85    86    Michael McCloy  Carnethy HRC  M40  00:46:03        5
89    90       Euan Easson  Carnethy HRC    M  00:46:38       14
91    92        Rosie Knox  Carnethy HRC    F  00:46:46        7
119  120     Craig Addison  Carnethy HRC  M50  00:50:54        3
124  125        Gary Walsh  Carnethy HRC    M  00:51:57       15
129  130    Rebecca Slater  Carnethy HRC    F  00:52:28        8
140  141    Shane Bouchier  Carnethy HRC  M40  00:53:56        6
142  143      Rachael Paul  Carnethy HRC    F  00:54:29        9
146  147    Morag McIntyre  Carnethy HRC  F65  00:55:11        1
156  157       Nicki Innes  Carnethy HRC  F55  00:56:49        1
164  165      Lucy Ritchie  Carnethy HRC    F  00:59:02       10
168  169      Amanda Lenzi  Carnethy HRC    F  01:01:01       11
170  171       Brian Howie  Carnethy HRC  M70  01:01:58        1

In [58]:
data

dict_keys(['Cobbler', 'Mamores', 'Traprain', 'Allermuir', 'Arrochar', 'Blisco', 'Moffat', 'Caerketton', 'Tap O North', 'Perris Horseshoe', 'Caerketton Down', 'Run O Mill', 'Manor Water', 'Skyloop', 'Tinto'])

In [63]:

# Example of your data dictionary (replace this with your actual data)
# Assuming data is a dictionary where keys are race names and values are dataframes
# Also assuming that each dataframe already has the 'Cat Pos' column populated
# Example: data = {'race1': df1, 'race2': df2, ... }

# Function to create a table with the best 6 races and total points for each runner and category
def create_runner_points_table(data):
    # Initialize an empty dataframe to accumulate the results
    runner_points = pd.DataFrame(columns=['Runner', 'Cat', 'Cat Pos'])

    # Loop through each race in the data dictionary
    for race, df in data.items():
        if race in NON_SHR:
            continue
        print(race, df.columns)

        # Ensure 'Cat Pos' is numeric (convert if necessary)
        df['Cat Pos'] = pd.to_numeric(df['Cat Pos'], errors='coerce')
        
        # Check if conversion worked
        if df['Cat Pos'].isnull().any():
            print(f"Warning: Some 'Cat Pos' values are invalid in {race}, converting them to NaN")
        print(df['Cat Pos'])
        # Group by 'Runner' and 'Cat' and take 'Cat Pos' for each runner in each category
        race_points = df[['Runner', 'Cat', 'Cat Pos']]

        # Append the points to the accumulated table of runner points
        runner_points = pd.concat([runner_points, race_points], ignore_index=True)

    # For each runner and category, we want to get the best 6 results (lowest Cat Pos)
    runner_points_sorted = runner_points.groupby(['Runner', 'Cat']).apply(
        lambda x: x.nsmallest(6, 'Cat Pos')  # Select the best 6 results (lowest Cat Pos)
    ).reset_index(drop=True)

    # Now sum the Cat Pos for each runner and category (best 6 results)
    runner_points_total = runner_points_sorted.groupby(['Runner', 'Cat'])['Cat Pos'].sum().reset_index()

    # Sort by total points (lowest points = best performance)
    runner_points_total = runner_points_total.sort_values(by='Cat Pos', ascending=True).reset_index(drop=True)

    return runner_points_total

# Example usage (assuming 'data' is your dictionary of dataframes):
runner_points_table = create_runner_points_table(data)

# Display the table
print(runner_points_table)

Cobbler Index(['Pos', 'Runner', 'Club', 'Cat', 'Time', 'CatPos', 'Cat Pos'], dtype='object')
4       1
5       2
8       3
9       4
13      1
14      1
15      2
23      1
28      1
29      2
34      3
36      4
37      5
38      6
41      7
45      8
51      9
56     10
58     11
64     12
95     13
106    14
114    15
115     1
117     2
121     3
125     4
151     5
161     1
165     2
174     1
183     2
190     1
Name: Cat Pos, dtype: int64
Mamores Index(['Pos', 'Runner', 'Club', 'Cat', 'Time', 'Cat Pos'], dtype='object')
2      1
11     2
12     3
15     4
18     1
20     1
27     5
38     1
68     2
74     1
77     3
101    2
120    2
Name: Cat Pos, dtype: int64
Traprain Index(['Pos', 'Runner', 'Club', 'Cat', 'Time', 'Cat Pos'], dtype='object')
0     1
6     1
8     2
10    1
13    3
14    2
19    2
20    4
24    5
28    6
31    3
35    4
37    1
38    1
40    2
42    1
53    3
56    3
61    1
68    1
69    2
72    7
Name: Cat Pos, dtype: int64
Allermuir Index(['Pos', 'Runner', 'Club', 'Cat', 'Time', 'Cat Pos'], dtype='object')
0      1
1      2
4      3
6      4
9      1
13     5
14     1
15     6
16     7
17     2
20     8
23     3
29     9
30     2
34     1
36     4
39     1
45     1
46     1
48     2
49     3
51     3
52     1
53     4
54     2
55     2
59     2
60    10
Name: Cat Pos, dtype: int64
Arrochar Index(['Pos', 'Runner', 'Club', 'Cat', 'Time', 'Cat Pos'], dtype='object')
3     1
5     2
9     3
12    4
13    5
22    6
23    7
24    8
27    1
30    2
33    3
42    1
63    9
96    2
Name: Cat Pos, dtype: int64
Moffat Index(['Pos', 'Runner', 'Club', 'Cat', 'Time', 'Cat Pos'], dtype='object')
5     1
9     1
15    2
23    3
26    1
67    1
69    1
80    2
Name: Cat Pos, dtype: int64
Caerketton Index(['Pos', 'Runner', 'Club', 'Cat', 'Time', 'Cat Pos'], dtype='object')
0      1
2      2
3      3
7      4
8      5
9      6
10     7
13     8
14     9
16    10
19     1
23     2
25    11
29     3
31    12
32    13
33    14
35     1
39    15
41     2
44     4
45     3
53     1
54     4
56    16
60     1
67     5
68     5
69    17
72     2
78     6
84     2
89     1
95     6
Name: Cat Pos, dtype: int64
Tap O North Index(['Pos', 'Runner', 'Club', 'Cat', 'Time', 'Cat Pos'], dtype='object')
11     1
13     2
17     1
31     2
62     1
71     1
93     2
109    1
Name: Cat Pos, dtype: int64
Caerketton Down Index(['Pos', 'Runner', 'Club', 'Cat', 'Time', 'Cat Pos'], dtype='object')
1     1
2     1
6     2
8     2
12    3
13    3
15    1
17    4
18    1
19    2
20    1
21    2
22    5
23    3
24    6
25    1
26    7
28    3
29    1
31    1
Name: Cat Pos, dtype: int64
Run O Mill Index(['Pos', 'Runner', 'Club', 'Cat', 'Time', 'Cat Pos'], dtype='object')
5     1
11    2
13    1
19    1
22    2
25    2
37    1
70    1
84    2
Name: Cat Pos, dtype: int64
Manor Water Index(['Pos', 'Runner', 'Club', 'Cat', 'Time', 'Cat Pos'], dtype='object')
2     1
3     1
4     2
5     2
8     1
13    1
15    1
17    2
21    3
22    3
23    4
25    3
27    1
32    1
33    2
35    5
36    3
37    2
38    2
41    3
42    4
43    6
45    4
46    5
48    1
Name: Cat Pos, dtype: int64
Skyloop Index(['Pos', 'Runner', 'Club', 'Cat', 'Time', 'Cat Pos'], dtype='object')
0       1
1       2
3       3
4       1
5       4
6       5
9       1
10      6
12      7
13      2
16      8
21      3
29      4
34      9
37     10
43     11
44      2
51      1
52     12
54      3
57     13
64      4
69      5
70      6
71      7
80      5
81      1
82     14
86      6
87      2
88      8
89      7
94     15
98     16
99      1
101     9
106    17
110    18
118     1
122    10
124     1
128    19
134     2
139    20
140     2
146     2
147    21
152    11
156     1
Name: Cat Pos, dtype: int64
Tinto Index(['Pos', 'Runner', 'Club', 'Cat', 'Time', 'Cat Pos'], dtype='object')
0       1
2       2
4       3
8       1
10      4
15      1
17      5
18      2
20      6
22      2
28      7
33      8
34      3
36      9
41      1
48     10
49      2
50      1
55      2
61     11
63      3
64      4
65     12
66      1
72      4
80     13
81      5
84      6
85      5
89     14
91      7
119     3
124    15
129     8
140     6
142     9
146     1
156     1
164    10
168    11
170     1
Name: Cat Pos, dtype: int64

TypeError: Column 'Cat Pos' has dtype object, cannot use method 'nsmallest' with this dtype